project:
  type: website

website:
  title: "R-Ladies Ottawa"
  favicon: images/favicon.ico
  page-navigation: true
  site-url: https://www.rladies-ottawa.github.io/
  reader-mode: true
  repo-url: https://github.com/RLadies-Ottawa/rladies-ottawa.github.io
  repo-actions: [edit, source, issue]
  page-footer:
    center:
      - href: index.qmd
        text: Home
  sidebar:
    title: R-Ladies Ottawa
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents:
      - href: index.qmd
        text: About
      - href: sponsors.qmd
        text: Sponsors
      - href: feedback.qmd
        text: Feedback
      - section: Events
        contents:
        - href: events/2024/iwd.qmd
          text: "International Women's Day Coding Challenge"
        - href: events/2024/intro_to_r.qmd
          text: "Introduction to R Workshop Series"
        
format:
  html:
    theme: 
      light: [minty, custom_light.scss]
      dark: [darkly, custom_dark.scss]
    toc: true