project:
  type: website

website:
  announcement: 
    content: "**New page alert** - Check out ['Events calender'](events.qmd) for upcoming events" 
  cookie-consent: true
  google-analytics: " G-L488CG8H5G"
  title: "R-Ladies Ottawa"
  favicon: images/favicon.ico
  page-navigation: true
  site-url: https://www.rladies-ottawa.github.io/
  reader-mode: true
  repo-url: https://github.com/RLadies-Ottawa/rladies-ottawa.github.io
  repo-actions: [edit, source, issue]
  page-footer:
    center:
      - href: index.qmd
        text: Home
  sidebar:
    title: R-Ladies Ottawa
    style: "docked"
    search: true
    collapse-level: 3
    logo: images/logo.png
    contents:
      - href: index.qmd
        text: About us
      - href: sponsors.qmd
      - href: events.qmd
        text: "Events calendar"
      - section: Links to events
        contents:
        - section: "2026"
          contents:
            - href: https://www.meetup.com/rladies-ottawa/events/312625100/
              text: "TidyTuesday"
        - section: "2025"
          contents:
            - href: https://www.meetup.com/rladies-ottawa/events/311779727/
              text: "Custom city maps in R"
            - href: https://www.meetup.com/rladies-ottawa/events/311256371/
              text: "R package development with GitHub Pages and `pkgdown`"
            - href: https://www.meetup.com/rladies-ottawa/events/308541470/
              text: "Networking and 5 à 7 - July"
            - href: events/2025/iwd.qmd
              text: "International Women's Day Coding Challenge"
            - href: https://www.meetup.com/rladies-ottawa/events/306232274/
              text: "Coding for a Cause with Claudie Larouche and ChatGPT"              
        - section: "2024"
          contents:            
            - href: https://www.meetup.com/rladies-ottawa/events/303388919/
              text: "posit::conf(2024) Watch Party"
            - href: https://www.meetup.com/rladies-ottawa/events/302456736/
              text: "Networking and 5 à 7 - August"
            - href: https://www.meetup.com/rladies-ottawa/events/301714279/
              text: "Networking and 5 à 7 - June"
            - href: https://www.meetup.com/rladies-ottawa/events/299893466/
              text: "Working with Big Data in R - Arrow Workshop"  
            - href: events/2024/intro_to_r.qmd
              text: "Introduction to R Workshop Series"
        - section: "2023"
          contents:
            - href: https://www.meetup.com/rladies-ottawa/events/296797478/
              text: "Lightning Talks"
            - href: https://www.meetup.com/rladies-ottawa/events/295826281/
              text: "In-person Networking Event"              
        - href: feedback.qmd
          text: Feedback

format:
  html:
    theme: 
      light: [pulse, custom_light.scss]
      dark: [darkly, custom_dark.scss]
    toc: true
